version: '4'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: book_service_db
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local
